version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: API-postgres
    environment:
      POSTGRES_DB: cadastro-API
      POSTGRES_USER: one
      POSTGRES_PASSWORD: 151719
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 